config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  resources :stores do
    get 'products', on: :member

    member do
      get :toggle_activation

      get 'products', to: 'stores#products'

      get 'orders/new', to: 'stores#new_order'  

    end
    resources :buyers, only: [:update]
    resources :orders, only: [:index, :create, :update, :destroy]
    resources :products, only: [:create, :index ]
    get'/orders/new' => 'stores#neworder'
    
  end
  resources :orders
  resources :orders, only: [:create, :index, :new] do
    member do 
      post 'approve'
    end
  end

  resources :buyers do
    member do
     get :toggle_activation
    end
  end

  get "listing" => "products#listing"
  post 'new' => 'registrations#create', as: :create_registration
  get 'me' => 'registrations#me'
  post 'sign_in' => 'registrations#sign_in'
  get 'products/store/:store_id' => 'products#products_store', as: :products_by_store
  scope :buyers do
    resources :orders, only: [:index, :create,:show, :update, :destroy]
  end
  
  root to: 'welcome#index'
  
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  before_validation :ensure_seller
  has_many :products
  has_one_attached :image
  before_validation :ensure_seller
  has_many :orders
  validates :name, presence: true, length: { minimum: 3 }
  validates :active, inclusion: { in: [true, false] }


  def deactivate!
    update(active: false)
  end

  def soft_delete
    update(deleted: true)
  end

  def undelete
    update(deleted: false)
  end

   def image_url
    Rails.application.routes.url_helpers.rails_blob_url(image, host: "localhost:3000") if image.attached?
  end
  private

  def ensure_seller
    self.user = nil if self.user && !self.user.seller?
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  skip_forgery_protection only: [:create, :update, :destroy]
  before_action :authenticate!, except: [:products] 
  before_action :set_store, only: %i[show edit update destroy]
  rescue_from User::InvalidToken, with: :not_authorized
  include ActionController::Live

  def index
    if current_user.present?
      if current_user.admin?
        @stores = Store.all
      else
        @stores = current_user.stores
      end
      respond_to do |format|
        format.html
        format.json { render json: @stores.map { |store| store.as_json(methods: :image_url) } }
      end
    else
      render json: { error: "Você deve estar logado para visualizar esta página." }, status: :unauthorized
    end
  end
  
  def show
    @store = Store.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @store.as_json(methods: :image_url) }
    end
  end

  def new
    @store = Store.new
    @sellers = User.where(role: :seller) if current_user.admin?
  end

  def edit
    @sellers = User.where(role: :seller) if current_user.admin?
  end

  def create
    @store = Store.new(store_params)
    @store.user = current_user unless current_user.admin?

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Loja criada com sucesso." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @store.update(store_params)
      @store.image.attach(params[:store][:image]) if params[:store][:image].present?
      render json: @store.as_json(methods: :image_url), status: :ok
    else
      render json: @store.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @store.soft_delete
      respond_to do |format|
        format.html { redirect_to stores_url, notice: "Loja excluída com sucesso." }
        format.json { render json: { message: "Loja excluída com sucesso." }, status: :ok }
      end
    else
      respond_to do |format|
        format.html { redirect_to stores_url, alert: "Falha ao excluir loja." }
        format.json { render json: { error: "Falha ao excluir loja." }, status: :unprocessable_entity }
      end
    end
  end

  def toggle_activation
    @store = Store.find(params[:id])
    if @store.active
      @store.update(active: false)
      flash[:notice] = "Loja desativada com sucesso."
    else
      @store.update(active: true)
      flash[:notice] = "Loja ativada com sucesso."
    end
    redirect_to stores_url
  end
  
  def products
    @store = Store.find(params[:id])
    @products = @store.products

    respond_to do |format|
      format.json { render json: @products }
    end
  end

  def new_order 
    response.headers["Content-Type"] = "text/event-stream"
    sse = SSE.new(response.stream, retry: 300, event: "waiting-orders")

    EventMachine.run do 
      periodic_timer = EventMachine::PeriodicTimer.new(3) do
      order = Order.where(store_id: params[:id], state: :created).last
      if order 
        message = { time: Time.now, order: order }
        sse.write(message, event: "new-order")
      else
        sse.write({ time: Time.now }, event: "no")
      end
    end
  end

  rescue IOError, ActionController::Live::ClientDisconnected
    sse.close if sse 
  ensure
    sse.close if sse  
  end
end

  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    required = params.require(:store)
    if current_user.admin?
      required.permit(:name, :user_id)
    else
      required.permit(:name)
    end
  end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  <% if current_user.admin? %>
    <div>
      <%= form.label :seller, style: "display: block" %>
      <%= form.collection_select :user_id, @sellers, :id, :email, prompt: "Sellers..." %>
    </div>
  <% end %>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stores</h1>

<div id="stores">
  <% @stores.each do |store| %>
    <%= render store %>
    <p>
      <%= link_to "Show this store", store %>
      <% if store.active? %>
      <%= link_to 'Desativar', toggle_activation_store_path(store), method: :patch, data: { confirm: 'Você tem certeza que deseja desativar este usuário?' } %>
    <% else %>
      <%= link_to 'Ativar', toggle_activation_store_path(store), method: :patch, data: { confirm: 'Você tem certeza que deseja ativar este usuário?' } %>
    <% end %>
      </td>
    </p>
  <% end %>
</div>

<%= link_to "New store", new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store %>

<div>
  <%= link_to "Edit this store", edit_store_path(@store) %> |
  <%= link_to "Back to stores", stores_path %>

  <%= button_to "Destroy this store", @store, method: :delete %>
</div>