config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  resources :stores do
    get 'products', on: :member

    member do
      get :toggle_activation

      get 'products', to: 'stores#products'

      get 'orders/new', to: 'stores#new_order'  

    end
    resources :buyers, only: [:update]
    resources :orders, only: [:index, :create, :update, :destroy]
    resources :products, only: [:create, :index ]
    get'/orders/new' => 'stores#neworder'
    
  end
  resources :orders
  resources :orders, only: [:create, :index, :new] do
    member do 
      post 'approve'
    end
  end

  resources :buyers do
    member do
     get :toggle_activation
    end
  end

  get "listing" => "products#listing"
  post 'new' => 'registrations#create', as: :create_registration
  get 'me' => 'registrations#me'
  post 'sign_in' => 'registrations#sign_in'
  get 'products/store/:store_id' => 'products#products_store', as: :products_by_store
  scope :buyers do
    resources :orders, only: [:index, :create,:show, :update, :destroy]
  end
  
  root to: 'welcome#index'
  
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/buyer.rb
class Buyer < ApplicationRecord
    belongs_to :user, optional: true
    accepts_nested_attributes_for :user
    validates :user, presence: true
    validate :user_must_be_buyer
    
    private
  
    def user_must_be_buyer
        return unless user
        
        errors.add(:user, 'must have role buyer') unless user.role == 'buyer'
      end
      
  end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  skip_forgery_protection only: [:create, :update, :destroy]
  before_action :authenticate!
  before_action :set_buyer, only: %i[show edit update destroy]
  rescue_from User::InvalidToken, with: :not_authorized
  before_action :authorize_buyer, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin?
      @buyers = Buyer.includes(:user).all
    else
      @buyers = [current_user.buyer]
    end
  end

  def show
  end

  def profile
    @buyer = current_user.buyer
    render json: @buyer.to_json(include: :user)
  end

  def new
    @buyer = Buyer.new
    @buyers = User.where(role: :buyer) if current_user.admin?
  end

  def edit
  end

  def create
    @buyer = Buyer.new(buyer_params)
    @buyer.user = current_user unless current_user.admin?

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to buyer_url(@buyer), notice: 'Comprador criado com sucesso.' }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @buyer.user.update(user_params)
        format.json { render json: @buyer.as_json(include: :user), status: :ok }
        format.html { redirect_to @buyer, notice: 'Comprador atualizado com sucesso.' }
      else
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
        format.html { render :edit }
      end
    end
  end
  def destroy
    @buyer.destroy
    redirect_to buyers_url, notice: 'Comprador excluído com sucesso.'
  end

  def toggle_activation
    @buyer = Buyer.find(params[:id])
    if @buyer.user.active?
      @buyer.user.update(active: false)
    else
      @buyer.user.update(active: true)
    end
    redirect_to buyers_url
  end

  private

 
  def set_buyer
    @buyer = params[:id] ? Buyer.find(params[:id]) : current_user.buyer
  end

  def buyer_params
    params.require(:buyer).permit(
      :user_id,
      user_attributes: [:name, :id, :email, :password, :password_confirmation]
    )
  end

  def user_params
    params.require(:buyer).require(:user_attributes).permit(:name, :email, :password, :password_confirmation, :role)
  end

  def authorize_buyer
    unless current_user.admin? || current_user == @buyer.user
      redirect_to buyers_url, alert: 'Você não tem permissão para acessar este comprador.'
    end
  end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_buyer.html.erb
<p>
  <strong>Nome:</strong>
  <%= @buyer.user.name if @buyer.user %>
</p>

<p>
  <strong>Email:</strong>
  <%= @buyer.user.email if @buyer.user %>
</p>

app/views/buyers/_form.html.erb
<%= form_with(model: @buyer, local: true) do |form| %>
  <% if @buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>
      <ul>
        <% @buyer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.fields_for :user do |user_form| %>
      <%= user_form.label :name %>
      <%= user_form.text_field :name %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buyers/edit.html.erb
<h1>Editing Buyer</h1>

<%= render "form", buyer: @buyer %>

<br>

<div>
  <%= link_to "Show this buyer", @buyer %> |
  <%= link_to "Back to buyers", buyers_path %>
</div>

app/views/buyers/index.html.erb
<h1>Compradores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
    <th>Email</th>
      
      <th colspan="4">Ações</th> <!-- Adicionando uma coluna extra para as ações -->
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= buyer.user.name %></td>
        <td><%= buyer.user.email %></td>

        <td><%= link_to 'Mostrar', buyer %></td>
        <td><%= link_to 'Editar', edit_buyer_path(buyer) %></td>
        <td>
        <% if buyer.user.active? %>
        <%= link_to 'Desativar', toggle_activation_buyer_path(buyer), method: :patch, data: { confirm: 'Você tem certeza que deseja desativar este usuário?' } %>
      <% else %>
        <%= link_to 'Ativar', toggle_activation_buyer_path(buyer), method: :patch, data: { confirm: 'Você tem certeza que deseja ativar este usuário?' } %>
      <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Comprador', new_buyer_path %>

app/views/buyers/new.html.erb
<%= form_with(model: @buyer, local: true) do |form| %>
  <% if @buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>
      <ul>
        <% @buyer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for :user, @buyer.build_user do |user_fields| %>
    <div class="field">
      <div class="field-label">
        <%= user_fields.label :email %>
      </div>
      <div class="field-input">
        <%= user_fields.email_field :email %>
      </div>
    </div>

    <div class="field">
      <div class="field-label">
        <%= user_fields.label :password %>
      </div>
      <div class="field-input">
        <%= user_fields.password_field :password %>
      </div>
    </div>

    <div class="field">
      <div class="field-label">
        <%= user_fields.label :password_confirmation %>
      </div>
      <div class="field-input">
        <%= user_fields.password_field :password_confirmation %>
      </div>
    </div>

    <%= user_fields.hidden_field :role, value: 'buyer' %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buyers/show.html.erb
<p>Email: <%= @buyer.user.email %></p>

<div>
  <%= link_to 'Editar', edit_buyer_path(@buyer) %> |
  <%= link_to 'Voltar', buyers_path %>
  <%= button_to "Destroy this buyer", @buyer, method: :delete %>
  </div>
</div>